### PR TITLE
Adding podman and local podman support.

### PR DESCRIPTION
**Pull request by elevisse**
In this pull request :
- adding config maps and podman yaml files
- adding specific scripts to backup and restore podman environment
- ignoring new podman files when installed by git clone process

Podman implementation documentation is updated by another pull request.

Tests done for this pull request :
- local podman in WSL 2 ubuntu 24.04
- podman classic with platform etienne.r2devops.tech (thanks to Thomas Boni)

### CODE REVIEW

**Comment by thomasboni** [comment]
Hello @elevisse , thanks for this contribution ! I have a few remarks:

1. It's great to have this podman configuration for our users, but as no one at R2Devops is knowing it, we cannot "officialy" support it. So, can you mention in podman configuration file, in the head comment, that this method is supported by the community ? 
2. Please update your commits messages to follow [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/). You can use `feat(podman): ...` 
3. Can you rebase your branch to not have a merge commit ?

**Comment by elevisse** [comment]
Hi @thomasboni. You are welcome.

Conventional commit is used. Mentions are inserted too.

**Comment by elevisse** [comment]
Last advice in demo ; 5 replicas for local worker.

**Review by thomasboni — APPROVED** [review]
Thanks for this contribution @elevisse ! All good :)

**Pull request merged**
